name: Continuous Deployment

on: workflow_dispatch

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“‚ Checkout code
        uses: actions/checkout@v6

      - name: ðŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ðŸ’š Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: ðŸ“¦ Install dependencies
        run: pnpm install

      - name: ðŸ”Ž Typecheck code
        run: pnpm typecheck

      - name: ðŸ”Ž Lint code
        run: pnpm lint

      - name: ðŸš€ Build code and deploy app
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOOLS_TOKEN: ${{ secrets.HOMEBREW_TOOLS_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
